/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventarioMateriales;

import BD.BDIngresosMaterial;
import Class.IngresoMaterial;
import java.util.ArrayList;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class ConsultaIngresosMateriales extends javax.swing.JInternalFrame {

    /**
     * Creates new form Existencias
     */
    public ConsultaIngresosMateriales() {
        initComponents();
        BuscarMateriales();
        descripcion.requestFocus();
    }

    private void BuscarMateriales() {
        ArrayList<IngresoMaterial> result = BDIngresosMaterial.ListarMateriales(descripcion.getText());
        cargarTabla(result);
    }

    private void cargarTabla(ArrayList<IngresoMaterial> list1) {

        Object[][] dato = new Object[list1.size()][2];
        int f = 0;
        for (IngresoMaterial a : list1) {
            
            dato[f][0] = a.getCodigo();
            dato[f][1] = a.getDescripcion();
            f++;
        }
        tabla.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                    "CODIGO","DESCRIPCION"
                }) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        });

        TableColumn columna1 = tabla.getColumn("CODIGO");
        columna1.setPreferredWidth(0);
        TableColumn columna2 = tabla.getColumn("DESCRIPCION");
        columna2.setPreferredWidth(200);
    }
    
    
    
    
    
    
    
    private void BuscarIngresosMateriales() {
        int a = (Integer.parseInt(String.valueOf(tabla.getModel().getValueAt(tabla.getSelectedRow(),0))));
        ArrayList<IngresoMaterial> result = BDIngresosMaterial.ListarMaterialesIngresados(a);
        cargarTablamate(result);
    }

    private void cargarTablamate(ArrayList<IngresoMaterial> list1) {

        Object[][] dato = new Object[list1.size()][8];
        int f = 0;
        for (IngresoMaterial a : list1) {
            
            dato[f][0] = a.getPN();
            dato[f][1] = a.getJob();
            dato[f][2] = a.getInvoice();
            dato[f][3] = a.getPO();
            dato[f][4] = a.getFechaString();
            dato[f][5] = a.getCantidad();
            dato[f][6] = a.getCantidadBodega();
            dato[f][7] = a.getNotas();
            f++;
        }
        todo.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                    "P/N","JOB","INVOICE","P.O","FECHA","CANTIDAD2","CANTIDAD","NOTA"
                }) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        });
        TableColumn columna1 = todo.getColumn("P/N");
        columna1.setPreferredWidth(0);
        TableColumn columna2 = todo.getColumn("JOB");
        columna2.setPreferredWidth(25);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        todo = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel1.setText("Descripcion ");

        descripcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcionKeyReleased(evt);
            }
        });

        todo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "P/N", "JOB", "INVOICE", "PO", "FECHA INGRESO", "CANTIDAD INGRESO", "CANTIDAD BODEGA", "NOTA"
            }
        ));
        jScrollPane2.setViewportView(todo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionKeyReleased
      BuscarMateriales();
    }//GEN-LAST:event_descripcionKeyReleased

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
       
        
       BuscarIngresosMateriales();
        
    }//GEN-LAST:event_tablaMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaIngresosMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaIngresosMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaIngresosMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaIngresosMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaIngresosMateriales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTable todo;
    // End of variables declaration//GEN-END:variables
}
