/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRABAJOS;

import BD.BDFIBRA;
import BD.DBDescripcion;
import BD.Trabajos;
import Class.CTrabajos;
import Class.DescripcionC;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class EditarJOBComponentes extends javax.swing.JInternalFrame {

    String accion = "";
    DefaultTableModel temp;
    int idcomponente;
    int ID_PN;
    String J;
    String PNt;
    int id_trabajo;
    int condescargas;
    int componentesagregados;

    /**
     * Creates new form Descri
     */
    public EditarJOBComponentes(String a, String b, int d) {
        this.PNt = a;
        this.J = b;
        this.id_trabajo = d;

        initComponents();
        BusquedaComponentesExitentes();
        BusquedaComponentesNuevos();

        try {
            CTrabajos c = Trabajos.BuscarTrabajo(d);
            PN.setText(c.getPn());
            REV.setText(c.getRev());
            FECHAIN.setText(c.getF1());
            FECHAVEN.setText(c.getF2());
            JOB.setText(c.getJob());
            CLIENTE.setText(c.getCliente());
            CANTIDAD.setText(String.valueOf(c.getCantidad1()));
        } catch (Exception e) {
            System.out.println("ERROR DE BUSCAR JOB ="+e);
        }

    }

    public void insertarNuevoCompo() {

        try {
            int cantidad = (Integer.parseInt(String.valueOf(TablaConNuevos.getModel().getValueAt(TablaConNuevos.getSelectedRow(), 2))));
            int compo = (Integer.parseInt(String.valueOf(TablaConNuevos.getModel().getValueAt(TablaConNuevos.getSelectedRow(), 0))));
            CTrabajos m = new CTrabajos();
            m.setIdcompo(compo);
            m.setIdTrabajo(id_trabajo);
            m.setCantidadportrabajo(Integer.parseInt(CANTIDAD.getText()) * cantidad);
            Trabajos.insertarNuevoComponente(m);
            /* System.out.println("1 = "+compo);
               System.out.println("2 = "+id_trabajo);
               System.out.println("1 = "+(Integer.parseInt(CANTIDAD.getText())*cantidad));*/
            BusquedaComponentesExitentes();
        } catch (Exception e) {
            System.out.println("Error BD:" + e);
        }

    }

    public void remover() {

        try {
            int compo = (Integer.parseInt(String.valueOf(TablaOriginalTrabajo.getModel().getValueAt(TablaOriginalTrabajo.getSelectedRow(), 1))));
            CTrabajos m = new CTrabajos();
            m.setIdcompo(compo);
            Trabajos.deleteComponente(m);
            BusquedaComponentesExitentes();
        } catch (Exception e) {
            System.out.println("Error BD:" + e.getMessage());
        }
    }
    
     public void VerificarDescargasComponentes(){
       int compodescarga = (Integer.parseInt(String.valueOf(TablaOriginalTrabajo.getModel().getValueAt(TablaOriginalTrabajo.getSelectedRow(), 0))));
        try {
            Connection c = BDFIBRA.getConnection();
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery("select COUNT(*) from entregas where no_trabajo = "+id_trabajo+" and idcompo ="+compodescarga);
            while (rs.next()){
               int lastID = rs.getInt(1);
               condescargas = lastID;
            }
            rs.close();
            stmt.close();
            c.close();
        } catch (SQLException error) {
            System.out.println(error);
        }
    }
     
     public void VerificarComponentesAgregados(){
       int compo = (Integer.parseInt(String.valueOf(TablaConNuevos.getModel().getValueAt(TablaConNuevos.getSelectedRow(), 0))));
        try {
            Connection c = BDFIBRA.getConnection();
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery("select COUNT(*) from trabajo_partes where no_trabajo = "+id_trabajo+" and idcompo ="+compo);
            while (rs.next()){
               int lastID = rs.getInt(1);
               componentesagregados = lastID;
            }
            rs.close();
            stmt.close();
            c.close();
        } catch (SQLException error) {
            System.out.println(error);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaOriginalTrabajo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaConNuevos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JOB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        REV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FECHAIN = new javax.swing.JTextField();
        CLIENTE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FECHAVEN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CANTIDAD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDITAR COMPONETES DE TRABAJO");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        TablaOriginalTrabajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "DESCRIPCION", "CANTIDAD"
            }
        ));
        TablaOriginalTrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaOriginalTrabajoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaOriginalTrabajo);

        TablaConNuevos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "DESCRIPCION", "CANTIDAD"
            }
        ));
        TablaConNuevos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConNuevosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaConNuevos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("COMPONENTES AGREGADOS RESIENTEMENTE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("COMPONENTES ACTUALES EN EL NUMERO DE TRABAJO ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("P/N");

        PN.setEditable(false);
        PN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PN.setForeground(new java.awt.Color(0, 51, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("JOB");

        JOB.setEditable(false);
        JOB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JOB.setForeground(new java.awt.Color(0, 51, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("REVISION");

        REV.setEditable(false);
        REV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        REV.setForeground(new java.awt.Color(0, 51, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("FECHA INGRESO");

        FECHAIN.setEditable(false);
        FECHAIN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FECHAIN.setForeground(new java.awt.Color(0, 51, 255));

        CLIENTE.setEditable(false);
        CLIENTE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLIENTE.setForeground(new java.awt.Color(0, 51, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("CLIENTE");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("FECHA VENCIMIENTO");

        FECHAVEN.setEditable(false);
        FECHAVEN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FECHAVEN.setForeground(new java.awt.Color(0, 51, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CANTIDAD");

        CANTIDAD.setEditable(false);
        CANTIDAD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CANTIDAD.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(JOB, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(PN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(REV, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CANTIDAD))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FECHAIN, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FECHAVEN)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FECHAIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FECHAVEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("AGREGAR O REMOVER COMPONENTES DE TABRAJO ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel10)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaOriginalTrabajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaOriginalTrabajoMouseClicked
/*        if (evt.getClickCount() > 1) {
            VerificarDescargasComponentes();
            if(condescargas == 0){remover();}else{JOptionPane.showMessageDialog(null, "EL COMPONENTE YA TIENE DESCARGAS NO SE PUEDE REMOVER");}
        }*/
    }//GEN-LAST:event_TablaOriginalTrabajoMouseClicked

    private void TablaConNuevosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConNuevosMouseClicked
        if (evt.getClickCount() > 1) {
            VerificarComponentesAgregados();
            if(componentesagregados == 0){insertarNuevoCompo();}else{JOptionPane.showMessageDialog(null, "EL COMPONENTE YA EXISTE EN EL P/N");}
            
        }
    }//GEN-LAST:event_TablaConNuevosMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
       //TablaPen.
    }//GEN-LAST:event_formInternalFrameClosed

    private void BusquedaComponentesNuevos() {
        ArrayList<DescripcionC> result = DBDescripcion.ListarComponentes(PNt);
        recargarTable(result);
    }

    public void recargarTable(ArrayList<DescripcionC> list) {
        Object[][] datos = new Object[list.size()][3];
        int i = 0;
        for (DescripcionC f : list) {
            datos[i][0] = f.getIdcompo();
            datos[i][1] = f.getDescripcion();
            datos[i][2] = f.getCantidad();
            i++;
        }
        TablaConNuevos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    "NO", "DESCRIPCION", "CANTIDAD"
                }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        TableColumn columna1 = TablaConNuevos.getColumn("NO");
        columna1.setPreferredWidth(0);
        TableColumn columna2 = TablaConNuevos.getColumn("DESCRIPCION");
        columna2.setPreferredWidth(200);
        TableColumn columna3 = TablaConNuevos.getColumn("CANTIDAD");
        columna3.setPreferredWidth(0);
    }
    private void BusquedaComponentesExitentes() {
        ArrayList<DescripcionC> result = DBDescripcion.ListarComponentesExistentes(J);
        recargarTableExistentes(result);
    }
    public void recargarTableExistentes(ArrayList<DescripcionC> list) {
        Object[][] datos = new Object[list.size()][3];
        int i = 0;
        for (DescripcionC f : list) {
            //datos[i][0] = f.getIdcompo();
            datos[i][0] = f.getId_pn();
            datos[i][1] = f.getDescripcion();
            datos[i][2] = f.getCantidad();
            i++;
        }
        TablaOriginalTrabajo.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    "NO", "DESCRIPCION", "CANTIDAD"
                }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
       /* TableColumn columna1 = TablaOriginalTrabajo.getColumn("ID");
        columna1.setPreferredWidth(0);*/
        TableColumn columna2 = TablaOriginalTrabajo.getColumn("NO");
        columna2.setPreferredWidth(0);
        TableColumn columna3 = TablaOriginalTrabajo.getColumn("DESCRIPCION");
        columna3.setPreferredWidth(200);
        TableColumn columna4 = TablaOriginalTrabajo.getColumn("CANTIDAD");
        columna4.setPreferredWidth(50);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CANTIDAD;
    private javax.swing.JTextField CLIENTE;
    private javax.swing.JTextField FECHAIN;
    private javax.swing.JTextField FECHAVEN;
    private javax.swing.JTextField JOB;
    private javax.swing.JTextField PN;
    private javax.swing.JTextField REV;
    private javax.swing.JTable TablaConNuevos;
    private javax.swing.JTable TablaOriginalTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
