/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRODUCTOS_INGRESADOS;

import ClassProductos.IngresoConsultaProductos;
import ClassProductos.ProductosTaller;
import java.util.ArrayList;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class ConsultaDescargas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaDescargas
     */
    public ConsultaDescargas() {
        initComponents();
        ListarPro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Producto = new javax.swing.JTable();
        descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Descargas = new javax.swing.JTable();
        Codigo = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        Producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO PRODUCTO", "DESCRIPCION"
            }
        ));
        Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Producto);

        descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcionKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DESCRIPCION DE PRODUCTO");

        Descargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Descargas);

        Codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CodigoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void ListarPro() {

        ArrayList<ProductosTaller>result = IngresoConsultaProductos.ListarTodosDescarga(descripcion.getText(),Codigo.getText());
        cargarTabla(result);
    }

    private void cargarTabla(ArrayList<ProductosTaller> list1) {

        Object[][] dato = new Object[list1.size()][2];
        int f = 0;
        for (ProductosTaller a : list1) {
            dato[f][0] = a.getCodigo_ingre();
            dato[f][1] = a.getDescripcion();
            f++;
        }
        Producto.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                "CODIGO","DESCRIPCION"
                }) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        });
         TableColumn columna1 = Producto.getColumn("CODIGO");
         columna1.setPreferredWidth(0);
         TableColumn columna2 = Producto.getColumn("DESCRIPCION");
         columna2.setPreferredWidth(250);
    }
    
    
     private void ListarDescargas() {
        int a =  Integer.parseInt(String.valueOf(Producto.getModel().getValueAt(Producto.getSelectedRow(), 0)));
        ArrayList<ProductosTaller>result = IngresoConsultaProductos.ListarDescargas(a);
        cargarTablaDescarga(result);
    }

    private void cargarTablaDescarga(ArrayList<ProductosTaller> list1) {

        Object[][] dato = new Object[list1.size()][9];
        int f = 0;
        for (ProductosTaller a : list1) {
            dato[f][0] = a.getFechaIngre();
            dato[f][1] = a.getPO();
            dato[f][2] = a.getCANTIDADINGRESO();
            dato[f][3] = a.getCantidad();
            dato[f][4] = a.getCANTIDAD();
            dato[f][5] = a.getFechaDesca();
            dato[f][6] = a.getPN();
            dato[f][7] = a.getJOB();
            dato[f][8] = a.getNOTA();
            
            
            f++;
        }
        Descargas.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                "FECHA INGRESO","P.O","CANTIDAD INGRESO","CANTIDAD DESCARGA","CANTIDAD EN BODEGA","FECHA DESCARGA","P/N","JOB","NOTA"
                }) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        });
         TableColumn columna1 = Descargas.getColumn("FECHA INGRESO");
         columna1.setPreferredWidth(80);
         TableColumn columna2 = Descargas.getColumn("P.O");
         columna2.setPreferredWidth(50);
          TableColumn columna3 = Descargas.getColumn("CANTIDAD INGRESO");
         columna3.setPreferredWidth(100);
          TableColumn columna4 = Descargas.getColumn("CANTIDAD DESCARGA");
         columna4.setPreferredWidth(100);
          TableColumn columna5 = Descargas.getColumn("CANTIDAD EN BODEGA");
         columna5.setPreferredWidth(110);
    }
        
   
    private void ProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoMouseClicked
        ListarDescargas();
        
    }//GEN-LAST:event_ProductoMouseClicked

    private void descripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionKeyReleased
        ListarPro();
    }//GEN-LAST:event_descripcionKeyReleased

    private void CodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoKeyReleased

                ListarPro();

    }//GEN-LAST:event_CodigoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo;
    private javax.swing.JTable Descargas;
    private javax.swing.JTable Producto;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
