/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRODUCTOS_INGRESADOS;

import ClassProductos.IngresoConsultaProductos;
import ClassProductos.ProductosTaller;
import java.util.ArrayList;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class ConsultaIngresos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaIngresos
     */
    public ConsultaIngresos() {
        initComponents();
        ListarPro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        Producto1 = new javax.swing.JTable();
        descripcion1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Producto = new javax.swing.JTable();
        descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ingresos = new javax.swing.JTable();
        Codigo = new javax.swing.JTextField();

        Producto1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO PRODUCTO", "DESCRIPCION"
            }
        ));
        Producto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Producto1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Producto1);

        descripcion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcion1KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DESCRIPCION DE PRODUCTO");

        setClosable(true);
        setTitle("CONSULTA DE INGRESOS ");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        Producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO PRODUCTO", "DESCRIPCION"
            }
        ));
        Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoMouseClicked(evt);
            }
        });
        Producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProductoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Producto);

        descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcionKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DESCRIPCION DE PRODUCTO");

        ingresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA_INGRESO", "P.O", "INVOICE", "CANTIDAD", "ESTANDAR"
            }
        ));
        ingresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ingresos);

        Codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CodigoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarPro() {

        ArrayList<ProductosTaller>result = IngresoConsultaProductos.ListarTodosProductos(descripcion.getText(),Codigo.getText());
        cargarTabla(result);
    }

    private void cargarTabla(ArrayList<ProductosTaller> list1) {

        Object[][] dato = new Object[list1.size()][2];
        int f = 0;
        for (ProductosTaller a : list1) {
            dato[f][0] = a.getCodigo_ingre();
            dato[f][1] = a.getDescripcion();
            f++;
        }
        Producto.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                "CODIGO","DESCRIPCION"
                }) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        });
         TableColumn columna1 = Producto.getColumn("CODIGO");
         columna1.setPreferredWidth(0);
         TableColumn columna2 = Producto.getColumn("DESCRIPCION");
         columna2.setPreferredWidth(250);
    }
    
    
private void ListarIngresosPro() {
        int f = Integer.parseInt(String.valueOf(Producto.getModel().getValueAt(Producto.getSelectedRow(), 0)));
        ArrayList<ProductosTaller>result = IngresoConsultaProductos.ListarTodosProductosIngresados(f);
        cargarTablaIngre(result);
    }

    private void cargarTablaIngre(ArrayList<ProductosTaller> list1) {

        Object[][] dato = new Object[list1.size()][7];
        int f = 0;
        for (ProductosTaller a : list1) {
            dato[f][0] = a.getId_ingreso();
            dato[f][1] = a.getFechaIngre();
            dato[f][2] = a.getPO();
            dato[f][3] = a.getINVOICE();
            dato[f][4] = a.getCANTIDAD();
            dato[f][5] = a.getCANTIDADINGRESO();
            dato[f][6] = a.getEstandarStr();
            f++;
        }
        ingresos.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                "ID","FECHA INGRESO","P.O","INVOICE","CANTIDAD EN BODEGA","CANTIDAD INGRESO","ESTANDAR"
                }) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        });
         TableColumn columna1 = ingresos.getColumn("ID");
         columna1.setPreferredWidth(0);
         TableColumn columna2 = ingresos.getColumn("FECHA INGRESO");
         columna2.setPreferredWidth(65);
    }    
    
    
    
    
    private void ProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoMouseClicked
        ListarIngresosPro();
        //buscarCantidad();
        //limpiar();
    }//GEN-LAST:event_ProductoMouseClicked

    private void descripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionKeyReleased
        ListarPro();
    }//GEN-LAST:event_descripcionKeyReleased

    private void ingresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresosMouseClicked
        //PN.requestFocus();
        //buscarIngreso();
        //Calendar c2 = new GregorianCalendar();
        //fecha.setCalendar(c2);
    }//GEN-LAST:event_ingresosMouseClicked

    private void Producto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Producto1MouseClicked
        ListarIngresosPro();
        //buscarCantidad();
        //limpiar();
    }//GEN-LAST:event_Producto1MouseClicked

    private void descripcion1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcion1KeyReleased
        ListarPro();
    }//GEN-LAST:event_descripcion1KeyReleased

    private void ProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProductoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoKeyPressed

    private void CodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoKeyReleased
         ListarPro();
    }//GEN-LAST:event_CodigoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo;
    private javax.swing.JTable Producto;
    private javax.swing.JTable Producto1;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField descripcion1;
    private javax.swing.JTable ingresos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
