/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BD.Entregas;
import Class.CEntregas;
import Class.IngresoMaterial;
import java.util.ArrayList;

/**
 *
 * @author jluis
 */
public class CDescargas extends javax.swing.JFrame {

    /**
     * Creates new form CDescargas
     */
    public CDescargas() {
        initComponents();
    }

    private void TablaHistorialEntregas() {

     //   ArrayList<CEntregas> result = Entregas.ListarHistorialEntregas(descrip.getText().toUpperCase());
      //  cargarTabla(result);
    }

    private void cargarTabla(ArrayList<CEntregas>list1) {

        Object[][] dato = new Object[list1.size()][7];
        int f = 0;
        for (CEntregas a : list1) {
            dato[f][0] = a.getPN();
            dato[f][1] = a.getDescripcion();
            dato[f][2] = a.getJOB();
            dato[f][3] = a.getPO();
            dato[f][4] = a.getCantidad();
            dato[f][5] = a.getFecha();
            dato[f][6] = a.getEmpleado();
            f++;
        }
        Descarga.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                "P/N","Descripcion","No. Trabajo","P.O","Cantidad Entregada","Fecha Entrega","Entregado A"
                }) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        });
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descarga = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        descrip = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        Descarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Fecha Ingreso", "P.O", "Invoice", "P/N", "Notas"
            }
        ));
        jScrollPane1.setViewportView(Descarga);

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel1.setText("Descripcion");

        descrip.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(descrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /*  private void TablaHistorialEntregas() {

        ArrayList<IngresoMaterial> result = Entregas.ListarHistorialEntregas(descrip.getText()job.getText().
                toUpperCase()));
        cargarTabla(result);
    }

    private void cargarTabla(ArrayList<IngresoMaterial> list1) {

        Object[][] dato = new Object[list1.size()][7];
        int f = 0;
        for (IngresoMaterial a : list1) {
            dato[f][0] = a.getDescripcion();
            dato[f][1] = a.getFechaIngreso();
            dato[f][3] = a.getPO();
            dato[f][5] = a.getInvoice();
            dato[f][2] = a.getPN();
            dato[f][4] = a.getCantidad();
            
            f++;
        }
        Descarga.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                "Descripcion","Fecha Ingreso","P.O","Invoice","P/N","Notas"
                }) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        });
    
    }
    */
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CDescargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CDescargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CDescargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CDescargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CDescargas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Descarga;
    private javax.swing.JTextField descrip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
