/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BD.BDFIBRA;
import BD.DBDescripcion;
import Class.DescripcionC;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class Descripcion extends javax.swing.JInternalFrame {
    
    String accion = "";

    /**
     * Creates new form IngresoFamilia
     */
    public Descripcion() {
    /*try {
             UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
             
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }*/
        initComponents();
        obtenerUltimoIdfam();
        BFeditar.setEnabled(false);
        BFguardar.setEnabled(false);
        BFNuevo.requestFocus();
        txtFDescripcion.setEditable(false);
        actualizarBusquedafam();
       // this.setLocationRelativeTo(null);
       
    }
    
    public void obtenerUltimoIdfam() {
        try {
            Connection con = BDFIBRA.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select max(iddesc) from Descripcion");
            while (rs.next()) {
                int lastID = rs.getInt(1);
                 txtId.setText(String.valueOf(lastID + 1));
            }
            rs.close();
            stmt.close();
            con.close();
        } catch (SQLException error) {
            System.out.print(error);
        }
    }
    
    public void limpiarCajaTextofam() {
        txtId.setText("");
        txtFDescripcion.setText("");
    }

    public void activarCajaTextofam(boolean b) {
        txtId.setEditable(!b);
        txtFDescripcion.setEditable(b);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BFNuevo = new javax.swing.JButton();
        BFguardar = new javax.swing.JButton();
        BFeditar = new javax.swing.JButton();
        BFcancelar = new javax.swing.JButton();
        txtFDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFMedida = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 204, 255));
        setClosable(true);
        setTitle("INGRESOS");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        BFNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BFNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/New.png"))); // NOI18N
        BFNuevo.setText("Nuevo");
        BFNuevo.setToolTipText("");
        BFNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFNuevoActionPerformed(evt);
            }
        });

        BFguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BFguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        BFguardar.setText("Guardar");
        BFguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFguardarActionPerformed(evt);
            }
        });

        BFeditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BFeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit2.png"))); // NOI18N
        BFeditar.setText("Editar");
        BFeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFeditarActionPerformed(evt);
            }
        });

        BFcancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BFcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        BFcancelar.setText("Cancelar");
        BFcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFcancelarActionPerformed(evt);
            }
        });

        txtFDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFDescripcionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("No.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Descripcion");

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BFNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BFguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BFeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BFcancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtFDescripcion))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BFcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtFMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Descripcion"
            }
        ));
        jtFMedida.setFocusable(false);
        jtFMedida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFMedidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFMedida);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtFMedidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFMedidaMouseClicked
        BFeditar.setEnabled(true);
        BFguardar.setEnabled(false);
        try {
            DescripcionC m = DBDescripcion.buscarDesc(Integer.parseInt(String.valueOf(jtFMedida.getModel().getValueAt(jtFMedida.getSelectedRow(),0))));
            txtId.setText(String.valueOf(m.getId()));
            txtFDescripcion.setText(m.getDescripcion());

        } catch (Exception e) {
            System.out.println("Erro de Seleccion:"+e);
        }
    }//GEN-LAST:event_jtFMedidaMouseClicked

    private void BFNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCajaTextofam();
        activarCajaTextofam(true);
        BFguardar.setEnabled(true);
        BFcancelar.setEnabled(true);
        BFNuevo.setEnabled(false);
        BFeditar.setEnabled(false);
        obtenerUltimoIdfam();
        accion = "Guardar";
        txtFDescripcion.setEditable(true);
        txtFDescripcion.requestFocus();
        
    }//GEN-LAST:event_BFNuevoActionPerformed

    private void BFguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFguardarActionPerformed
        
        if(accion.equalsIgnoreCase("Guardar")){

            if (txtId.getText().compareTo("")!=0 && txtFDescripcion.getText().compareTo("")!=0){
                try {
                    txtFDescripcion.setEditable(true);
                    DescripcionC m = new DescripcionC();
                    m.setDescripcion(txtFDescripcion.getText().toUpperCase());
                    m.setId(Integer.parseInt(txtId.getText()));
                    DBDescripcion.insertarDesc(m);
                    JOptionPane.showMessageDialog(null,"Registro Guardado");
                } catch (Exception e) {
                    System.out.println("Error BD:"+e.getMessage());
                }
                limpiarCajaTextofam();
                obtenerUltimoIdfam();
                actualizarBusquedafam();
                BFguardar.setEnabled(false);
                BFNuevo.requestFocus();
                BFNuevo.setEnabled(true);
                txtFDescripcion.setEditable(false);
              

            }else {
                JOptionPane.showMessageDialog(null,"Llene Todos Los Campos...");
            }
        }
        if (accion.equalsIgnoreCase("Actualizar")) {
            DescripcionC p;
            try {
                p= DBDescripcion.buscarDesc(Integer.parseInt(txtId.getText()));
                p.setDescripcion(txtFDescripcion.getText());
                DBDescripcion.actualizarFamilia(p);
                JOptionPane.showMessageDialog(null, " [ Datos Actualizados ]");
                limpiarCajaTextofam();
                obtenerUltimoIdfam();
                BFguardar.setEnabled(false);
                BFNuevo.setEnabled(true);
                actualizarBusquedafam();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_BFguardarActionPerformed

    private void BFeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFeditarActionPerformed
        accion = "Actualizar";
        activarCajaTextofam(true);
        BFNuevo.setEnabled(false);
        BFguardar.setEnabled(true);
        BFeditar.setEnabled(false);
        BFcancelar.setEnabled(true);
        txtFDescripcion.setEditable(true);
    }//GEN-LAST:event_BFeditarActionPerformed

    private void BFcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFcancelarActionPerformed
        limpiarCajaTextofam();
        obtenerUltimoIdfam();
        BFNuevo.setEnabled(true);
        BFguardar.setEnabled(false);
        BFeditar.setEnabled(false);
        txtFDescripcion.setEditable(false);
       
    }//GEN-LAST:event_BFcancelarActionPerformed

    private void txtFDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDescripcionActionPerformed
      BFguardar.requestFocus();
   
    }//GEN-LAST:event_txtFDescripcionActionPerformed

     private void actualizarBusquedafam() {
        ArrayList<DescripcionC> result = DBDescripcion.ListarDescrip();
        recargarTablefam(result);
    }
    
    public void recargarTablefam(ArrayList<DescripcionC> list) {
        Object[][] datos = new Object[list.size()][2];
        int i = 0;
        for (DescripcionC f : list)
        {
            datos[i][0] = f.getId();
            datos[i][1] = f.getDescripcion();
            i++;
        }
        jtFMedida.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    "No.","Descripcion"
                }) {
                     @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        
        TableColumn columna1 = jtFMedida.getColumn("No.");
        columna1.setPreferredWidth(0);
        TableColumn columna2 = jtFMedida.getColumn("Descripcion");
        columna2.setPreferredWidth(200);
    }
    
    
    /**
     * @param args the command line arguments
     */
    
         public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Descripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Descripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Descripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Descripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       // </editor-fold>
       // </editor-fold>
       // </editor-fold>
       // </editor-fold>
       // </editor-fold>
       // </editor-fold>
       // </editor-fold>
       // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Descripcion().setVisible(true);
            }
        });
}
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFNuevo;
    private javax.swing.JButton BFcancelar;
    private javax.swing.JButton BFeditar;
    private javax.swing.JButton BFguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtFMedida;
    private javax.swing.JTextField txtFDescripcion;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
